[workspace]
members = [".", "enumwow_helpers"]

[package]
name = "enumwow"
version = "0.0.0-reserved"
edition = "2024"

[dependencies]
enumwow_helpers = { path = "enumwow_helpers" }
const_format = "0.2"